ShaderLibrarySettings:
  CompilationSettings:
    AutoMapping: 0
    PreserveBindings: 0
    SuppressWarnings: 0
    WarningsAsErrors: 1
    InvertY: 0
    GenerateDebugInfo: 1
    Optimize: 1
    RecompileOnLoad: 1
    GLSLVersion: 460
    VulkanVersion: '[1,3,0]'
