GeneratorSettings:
  PixelRange: 10.0
  MinimumScale: 120
  Scale: 120
  MiterLimit: 1
  Padding: 0
  DimensionWidth: -1
  DimensionHeight: -1
  ExpensiveColoring: 1
  DimensionConstraint: NONE
  DefaultAngleThreshold: 3
  AttributeSettings:
    OverlapSupport: 1
    ScanlinePass: 1
    AtlasType: MTSDF
    ThreadCount: 8
